package model;
// Generated 21 juin 2019 14:34:53 by Hibernate Tools 4.3.1



/**
 * Agence generated by hbm2java
 */
public class Agence  implements java.io.Serializable {


     private int idagence;
     private String nom;
     private String horaires;
     private String telephone;
     private String adresse;

    public Agence() {
    }

    public Agence(int idagence, String nom, String horaires, String telephone, String adresse) {
       this.idagence = idagence;
       this.nom = nom;
       this.horaires = horaires;
       this.telephone = telephone;
       this.adresse = adresse;
    }
   
    public int getIdagence() {
        return this.idagence;
    }
    
    public void setIdagence(int idagence) {
        this.idagence = idagence;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getHoraires() {
        return this.horaires;
    }
    
    public void setHoraires(String horaires) {
        this.horaires = horaires;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }




}


