package model;
// Generated 21 juin 2019 14:34:53 by Hibernate Tools 4.3.1



/**
 * Clientcompte generated by hbm2java
 */
public class Clientcompte  implements java.io.Serializable {


     private ClientcompteId id;

    public Clientcompte() {
    }

    public Clientcompte(ClientcompteId id) {
       this.id = id;
    }
   
    public ClientcompteId getId() {
        return this.id;
    }
    
    public void setId(ClientcompteId id) {
        this.id = id;
    }




}


