package model;
// Generated 21 juin 2019 14:34:53 by Hibernate Tools 4.3.1



/**
 * ClientcompteId generated by hbm2java
 */
public class ClientcompteId  implements java.io.Serializable {


     private int idclient;
     private String ibancompte;

    public ClientcompteId() {
    }

    public ClientcompteId(int idclient, String ibancompte) {
       this.idclient = idclient;
       this.ibancompte = ibancompte;
    }
   
    public int getIdclient() {
        return this.idclient;
    }
    
    public void setIdclient(int idclient) {
        this.idclient = idclient;
    }
    public String getIbancompte() {
        return this.ibancompte;
    }
    
    public void setIbancompte(String ibancompte) {
        this.ibancompte = ibancompte;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClientcompteId) ) return false;
		 ClientcompteId castOther = ( ClientcompteId ) other; 
         
		 return (this.getIdclient()==castOther.getIdclient())
 && ( (this.getIbancompte()==castOther.getIbancompte()) || ( this.getIbancompte()!=null && castOther.getIbancompte()!=null && this.getIbancompte().equals(castOther.getIbancompte()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdclient();
         result = 37 * result + ( getIbancompte() == null ? 0 : this.getIbancompte().hashCode() );
         return result;
   }   


}


