package model;
// Generated 21 juin 2019 14:34:53 by Hibernate Tools 4.3.1

import java.util.Set;




/**
 * Compte generated by hbm2java
 */
public class Compte  implements java.io.Serializable {


     private String iban;
     private Set<Client> clients;
     private Set<Operation> entrees;
     private Set<Operation> sorties;
     private double solde;

    public Compte() {
    }

    public Compte(String iban, double solde) {
       this.iban = iban;
       this.solde = solde;
    }
   
    public String getIban() {
        return this.iban;
    }
    public void setIban(String iban) {
        this.iban = iban;
    }
    public double getSolde() {
        return this.solde;
    }
    public void setSolde(double solde) {
        this.solde = solde;
    }
    public Set<Client> getClients() {
        return clients;
    }
    public void setClients(Set<Client> clients) {
        this.clients = clients;
    }
    public Set<Operation> getEntrees() {
        return entrees;
    }
    public void setEntrees(Set<Operation> entrees) {
        this.entrees = entrees;
    }
    public Set<Operation> getSorties() {
        return sorties;
    }
    public void setSorties(Set<Operation> sorties) {
        this.sorties = sorties;
    }
}


