package model;
// Generated 21 juin 2019 14:34:53 by Hibernate Tools 4.3.1



/**
 * Conseiller generated by hbm2java
 */
public class Conseiller extends Utilisateur {


     private int idconseiller;
     private String login;
     private String pwd;
     private String nom;
     private String prenom;
     private String adresse;
     private String telephone;
     private String mail;
     private Agence agence;

    public Conseiller() {
    }

    public Conseiller(int idconseiller, String login, String pwd, String nom, String prenom, String adresse, String telephone, String mail, Agence agence) {
       super(login, pwd, nom, prenom, adresse, telephone, mail);
       this.idconseiller = idconseiller;
       this.agence = agence;
    }
   
    public int getIdconseiller() {
        return this.idconseiller;
    }
    
    public void setIdconseiller(int idconseiller) {
        this.idconseiller = idconseiller;
    }
    public Agence getIdagence() {
        return this.agence;
    }
    
    public void setIdagence(Agence agence) {
        this.agence = agence;
    }




}


