package model;
// Generated 21 juin 2019 14:34:53 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private int idmessage;
     private int idclient;
     private Date date;
     private String contenu;

    public Message() {
    }

    public Message(int idmessage, int idclient, Date date, String contenu) {
       this.idmessage = idmessage;
       this.idclient = idclient;
       this.date = date;
       this.contenu = contenu;
    }
   
    public int getIdmessage() {
        return this.idmessage;
    }
    
    public void setIdmessage(int idmessage) {
        this.idmessage = idmessage;
    }
    public int getIdclient() {
        return this.idclient;
    }
    
    public void setIdclient(int idclient) {
        this.idclient = idclient;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getContenu() {
        return this.contenu;
    }
    
    public void setContenu(String contenu) {
        this.contenu = contenu;
    }




}


