package model;
// Generated 21 juin 2019 14:34:53 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Operation generated by hbm2java
 */
public class Operation  implements java.io.Serializable, Comparable {


     private int idoperation;
     private Compte source;
     private Compte destinataire;
     private Date date;
     private double montant;
     private String libelle;

    public Operation() {
    }

	
    public Operation(int idoperation, Date date, double montant) {
        this.idoperation = idoperation;
        this.date = date;
        this.montant = montant;
    }
    public Operation(int idoperation, Compte source, Compte destinataire, Date date, double montant, String libelle) {
       this.idoperation = idoperation;
       this.source = source;
       this.destinataire = destinataire;
       this.date = date;
       this.montant = montant;
       this.libelle = libelle;
    }
   
    public int getIdoperation() {
        return this.idoperation;
    }
    public void setIdoperation(int idoperation) {
        this.idoperation = idoperation;
    }
    public Compte getSource() {
        return this.source;
    }
    public void setSource(Compte source) {
        this.source = source;
    }
    public Compte getDestinataire() {
        return this.destinataire;
    }
    public void setDestinataire(Compte destinataire) {
        this.destinataire = destinataire;
    }
    public Date getDate() {
        return this.date;
    }
    public void setDate(Date date) {
        this.date = date;
    }
    public double getMontant() {
        return this.montant;
    }
    public void setMontant(double montant) {
        this.montant = montant;
    }
    public String getLibelle() {
        return libelle;
    }
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
    
    @Override
    public int compareTo(Object o) {
        if (!(o instanceof Operation))
            throw new IllegalArgumentException("Operation > compareTo > parameter is not an Operation " + o);
        Operation other = (Operation) o;
        return this.getDate().compareTo(other.getDate());
    }
}


