package model;
// Generated 21 juin 2019 14:34:53 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Operation generated by hbm2java
 */
public class Operation  implements java.io.Serializable {


     private int idoperation;
     private String ibansource;
     private String ibandestinataire;
     private Date date;
     private double montant;

    public Operation() {
    }

	
    public Operation(int idoperation, Date date, double montant) {
        this.idoperation = idoperation;
        this.date = date;
        this.montant = montant;
    }
    public Operation(int idoperation, String ibansource, String ibandestinataire, Date date, double montant) {
       this.idoperation = idoperation;
       this.ibansource = ibansource;
       this.ibandestinataire = ibandestinataire;
       this.date = date;
       this.montant = montant;
    }
   
    public int getIdoperation() {
        return this.idoperation;
    }
    
    public void setIdoperation(int idoperation) {
        this.idoperation = idoperation;
    }
    public String getIbansource() {
        return this.ibansource;
    }
    
    public void setIbansource(String ibansource) {
        this.ibansource = ibansource;
    }
    public String getIbandestinataire() {
        return this.ibandestinataire;
    }
    
    public void setIbandestinataire(String ibandestinataire) {
        this.ibandestinataire = ibandestinataire;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public double getMontant() {
        return this.montant;
    }
    
    public void setMontant(double montant) {
        this.montant = montant;
    }




}


